apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-deployment
spec:
  selector:
    matchLabels:
      app: orders-mongo
  template:
    metadata:
      labels:
        app: orders-mongo
    spec:
      containers:
      - name: orders-mongo
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
