import { Button } from '@mui/material';
import Head from 'next/head'
import Image from 'next/image'
import { getSession, signOut } from 'next-auth/client';
//import axios from 'axios';

import styles from '../styles/Home.module.css'
import { getAuth } from '../utils/getAuth';
import AuthAppBar from '../components/AuthAppBar';

export default function Home(props) { 
  const { session } = props; 
  const authInfo = getAuth(session.user.email); 
  const logoutHandler = () => {
    signOut();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
      <AuthAppBar session={session} signOut={signOut}/>
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Ticketing K8s!</a>
        </h1>

        <p className={styles.description}>
          {`Your are ${authInfo && authInfo.token? 'Logged in': 'not logged in.'}`}
        </p>
        <div style={{margin: '1rem 0'}}></div>
        <Button variant="text" onClick={logoutHandler}>Logout</Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context){
  const session = await getSession({req: context.req});
  if(!session) {
    return {
      redirect: {
        destination: '/auth/login',
        permanent: false
      }
    }
  }
  return {
    props: {
      session
    }
  }
}
